# Netlify Configuration for Madox Homes Sites
[build]
  publish = "."
  command = "echo 'Building Madox Homes Sites...'"

[build.environment]
  NODE_VERSION = "18"

# Redirects for clean URLs and property access
[[redirects]]
  from = "/property/:slug"
  to = "/properties/:slug.html"
  status = 200

[[redirects]]
  from = "/calvary"
  to = "/properties/calvary-estate-advanced.html"
  status = 200

[[redirects]]
  from = "/sandbeach"
  to = "/properties/sandbeach-resort-advanced.html"
  status = 200

[[redirects]]
  from = "/edem-nike"
  to = "/properties/edem-nike-estate-advanced.html"
  status = 200

[[redirects]]
  from = "/lady-mabel"
  to = "/properties/lady-mabel-estate-advanced.html"
  status = 200

[[redirects]]
  from = "/sandeach"
  to = "/properties/sandeach-estate-extension.html"
  status = 200

[[redirects]]
  from = "/madox-centenary"
  to = "/properties/madox-centenary-estate.html"
  status = 200

[[redirects]]
  from = "/zoo-estate"
  to = "/properties/zoo-estate.html"
  status = 200

[[redirects]]
  from = "/nza-hotel"
  to = "/properties/nza-street-hotel.html"
  status = 200

# SPA fallback for any other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.arcgisonline.com https://*.openstreetmap.org https://*.tile.openstreetmap.org https://unpkg.com https://wa.me data: blob:; img-src 'self' data: blob: https://*.arcgisonline.com https://*.openstreetmap.org; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://unpkg.com;"

# Cache headers for static assets
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Enable gzip compression
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# PWA support
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"